--
-- PostgreSQL database dump
--

\restrict mh93ESUc69252F9VOVHfR7XglONoPxg3TdLv0sFdgYiugOgSia5CCczkHj0Cria

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: estanteria_user
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO estanteria_user;

--
-- Name: estado_estanteria; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.estado_estanteria AS ENUM (
    'CREADA',
    'ACTUALIZADA',
    'LISTA'
);


ALTER TYPE public.estado_estanteria OWNER TO postgres;

--
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'ADMIN',
    'WORKER',
    'SUPERADMIN'
);


ALTER TYPE public.user_role OWNER TO postgres;

--
-- Name: userrole; Type: TYPE; Schema: public; Owner: estanteria_user
--

CREATE TYPE public.userrole AS ENUM (
    'ADMIN',
    'SUPERADMIN',
    'WORKER'
);


ALTER TYPE public.userrole OWNER TO estanteria_user;

--
-- Name: CAST (public.userrole AS character varying); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (public.userrole AS character varying) WITH INOUT AS IMPLICIT;


--
-- Name: CAST (character varying AS public.userrole); Type: CAST; Schema: -; Owner: -
--

CREATE CAST (character varying AS public.userrole) WITH INOUT AS IMPLICIT;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: inspeccion; Type: TABLE; Schema: public; Owner: estanteria_user
--

CREATE TABLE public.inspeccion (
    inspeccion_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    estanteria_codigo character varying(50) NOT NULL,
    notas text,
    imagen_path character varying(255),
    estado character varying(20) DEFAULT 'CREADA'::public.estado_estanteria NOT NULL
);


ALTER TABLE public.inspeccion OWNER TO estanteria_user;

--
-- Name: inspeccion_inspeccion_id_seq; Type: SEQUENCE; Schema: public; Owner: estanteria_user
--

CREATE SEQUENCE public.inspeccion_inspeccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inspeccion_inspeccion_id_seq OWNER TO estanteria_user;

--
-- Name: inspeccion_inspeccion_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: estanteria_user
--

ALTER SEQUENCE public.inspeccion_inspeccion_id_seq OWNED BY public.inspeccion.inspeccion_id;


--
-- Name: inspeccion_slot_resultado; Type: TABLE; Schema: public; Owner: estanteria_user
--

CREATE TABLE public.inspeccion_slot_resultado (
    slot_resultado_id bigint NOT NULL,
    confianza double precision NOT NULL,
    estado_visual character varying(20) NOT NULL,
    orden integer NOT NULL,
    slot_id character varying(50) NOT NULL,
    inspeccion_id bigint NOT NULL,
    CONSTRAINT inspeccion_slot_resultado_estado_visual_check CHECK (((estado_visual)::text = ANY ((ARRAY['OCUPADO'::character varying, 'VACIO'::character varying, 'ANOMALIA'::character varying])::text[])))
);


ALTER TABLE public.inspeccion_slot_resultado OWNER TO estanteria_user;

--
-- Name: inspeccion_slot_resultado_slot_resultado_id_seq; Type: SEQUENCE; Schema: public; Owner: estanteria_user
--

ALTER TABLE public.inspeccion_slot_resultado ALTER COLUMN slot_resultado_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inspeccion_slot_resultado_slot_resultado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: estanteria_user
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    token character varying(120) NOT NULL,
    used_at timestamp(6) with time zone,
    user_account_id bigint NOT NULL
);


ALTER TABLE public.password_reset_token OWNER TO estanteria_user;

--
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: estanteria_user
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_account; Type: TABLE; Schema: public; Owner: estanteria_user
--

CREATE TABLE public.user_account (
    id bigint NOT NULL,
    username character varying(80) NOT NULL,
    email character varying(120) NOT NULL,
    password_hash character varying(200) NOT NULL,
    role public.user_role NOT NULL,
    company_id bigint,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone
);


ALTER TABLE public.user_account OWNER TO estanteria_user;

--
-- Name: user_account_id_seq; Type: SEQUENCE; Schema: public; Owner: estanteria_user
--

CREATE SEQUENCE public.user_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_account_id_seq OWNER TO estanteria_user;

--
-- Name: user_account_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: estanteria_user
--

ALTER SEQUENCE public.user_account_id_seq OWNED BY public.user_account.id;


--
-- Name: inspeccion inspeccion_id; Type: DEFAULT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.inspeccion ALTER COLUMN inspeccion_id SET DEFAULT nextval('public.inspeccion_inspeccion_id_seq'::regclass);


--
-- Name: user_account id; Type: DEFAULT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.user_account ALTER COLUMN id SET DEFAULT nextval('public.user_account_id_seq'::regclass);


--
-- Data for Name: inspeccion; Type: TABLE DATA; Schema: public; Owner: estanteria_user
--

COPY public.inspeccion (inspeccion_id, created_at, estanteria_codigo, notas, imagen_path, estado) FROM stdin;
6	2026-03-08 15:29:53.726559	EST-001	\N	capture_000013.png	CREADA
7	2026-03-08 15:32:13.282506	EST-001	\N	capture_000014.png	CREADA
8	2026-03-08 16:08:23.954593	EST-001	\N	capture_000015.png	CREADA
9	2026-03-08 16:14:07.757118	EST-001	\N	capture_000016.png	CREADA
10	2026-03-08 17:24:47.99849	EST-001	\N	capture_000017.png	CREADA
11	2026-03-08 17:26:47.916035	EST-001	Los productos estaban muy oscuros.	capture_000018.png	CREADA
12	2026-03-13 16:57:18.732966	EST-01	Hueco confirmado tras revisión manual	capture_000016.png	ACTUALIZADA
13	2026-04-19 17:40:31.797333	EST-001	\N	capture_000019.png	CREADA
\.


--
-- Data for Name: inspeccion_slot_resultado; Type: TABLE DATA; Schema: public; Owner: estanteria_user
--

COPY public.inspeccion_slot_resultado (slot_resultado_id, confianza, estado_visual, orden, slot_id, inspeccion_id) FROM stdin;
\.


--
-- Data for Name: password_reset_token; Type: TABLE DATA; Schema: public; Owner: estanteria_user
--

COPY public.password_reset_token (id, created_at, expires_at, token, used_at, user_account_id) FROM stdin;
1	2026-03-09 16:46:50.099467+01	2026-03-09 17:16:50.099467+01	b466e324-dee2-487e-8e92-ac3d84c44cd0	2026-03-09 16:53:18.26428+01	1
2	2026-03-09 16:53:18.272788+01	2026-03-09 17:23:18.272788+01	ea94c978-0e5a-437f-8daa-b5f4fbb140df	2026-03-09 16:53:58.129633+01	1
3	2026-03-09 21:30:16.880735+01	2026-03-09 22:00:16.880735+01	9c61c801-2ca1-436a-9bb4-8336ff1376bb	2026-03-13 10:11:09.748986+01	1
4	2026-03-13 10:11:09.803088+01	2026-03-13 10:41:09.803088+01	60c92853-8780-4e4c-af9d-b9d2106514f8	2026-03-13 10:19:15.382984+01	1
5	2026-03-13 10:19:15.415408+01	2026-03-13 10:49:15.415408+01	6bc75583-ee10-41b2-b1c4-2b795e0d92c8	2026-03-13 11:01:52.562596+01	1
6	2026-03-13 11:01:52.591667+01	2026-03-13 11:31:52.591667+01	d21892d2-f5a4-4f85-98a8-aff0b2accfbb	2026-03-13 11:27:39.630343+01	1
7	2026-04-10 13:07:08.069869+02	2026-04-10 13:37:08.069869+02	51a96829-fd26-4c20-8023-12c1870e7c47	2026-04-10 13:07:44.08072+02	5
8	2026-04-19 18:00:39.419067+02	2026-04-19 18:30:39.419067+02	39215cf7-230f-4738-b98c-346b55138f78	2026-04-19 18:01:10.174189+02	1
\.


--
-- Data for Name: user_account; Type: TABLE DATA; Schema: public; Owner: estanteria_user
--

COPY public.user_account (id, username, email, password_hash, role, company_id, enabled, created_at, updated_at, last_login_at) FROM stdin;
3	admin	admin@example.com	$2a$10$vvqjoMlhXxjkCbmU5r6DA.mR.ydTPFtnjf1ILPUYkALsCZQs7v2fO	ADMIN	\N	t	2026-02-26 23:28:55.013101+01	2026-02-26 23:28:55.013101+01	\N
4	worker	worker@example.com	$2a$10$uE7rOLM7Dib8eD89oMh5WuBauchOIL.TP8ny8/k0ny4R0inJ3a.1y	WORKER	\N	t	2026-02-26 23:28:55.087139+01	2026-02-26 23:28:55.087139+01	\N
6	pepeitoJose	jesusgil@hotmail.com	$2a$10$PRc4m2WMBERzoIPVYZwISe.9lVJaIEYQd5.SGK3tU.PoI3GuuD8hu	WORKER	\N	t	2026-03-09 21:26:36.65472+01	2026-03-09 21:26:36.65472+01	\N
5	Ana	imbalacio12@gmail.com	$2a$10$fqja3MOaQ/Wfc8MTySP84eUPb/QoisZXcta3ee/H1XZ.LBjxRvpWS	WORKER	\N	t	2026-02-28 22:59:06.768058+01	2026-02-28 22:59:06.768058+01	\N
1	superadmin	lacio161@gmail.com	$2a$10$u8lIpsTNRjcQEfv3JKCYvunOa/h9ITj1hEO9F4zPbDmt2p/oVEnZO	SUPERADMIN	\N	t	2026-02-26 23:19:47.599808+01	2026-02-26 23:19:47.599808+01	\N
\.


--
-- Name: inspeccion_inspeccion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: estanteria_user
--

SELECT pg_catalog.setval('public.inspeccion_inspeccion_id_seq', 13, true);


--
-- Name: inspeccion_slot_resultado_slot_resultado_id_seq; Type: SEQUENCE SET; Schema: public; Owner: estanteria_user
--

SELECT pg_catalog.setval('public.inspeccion_slot_resultado_slot_resultado_id_seq', 1, false);


--
-- Name: password_reset_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: estanteria_user
--

SELECT pg_catalog.setval('public.password_reset_token_id_seq', 8, true);


--
-- Name: user_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: estanteria_user
--

SELECT pg_catalog.setval('public.user_account_id_seq', 6, true);


--
-- Name: inspeccion inspeccion_pkey; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.inspeccion
    ADD CONSTRAINT inspeccion_pkey PRIMARY KEY (inspeccion_id);


--
-- Name: inspeccion_slot_resultado inspeccion_slot_resultado_pkey; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.inspeccion_slot_resultado
    ADD CONSTRAINT inspeccion_slot_resultado_pkey PRIMARY KEY (slot_resultado_id);


--
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- Name: user_account uk_user_account_email; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT uk_user_account_email UNIQUE (email);


--
-- Name: user_account uk_user_account_username; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT uk_user_account_username UNIQUE (username);


--
-- Name: password_reset_token ukg0guo4k8krgpwuagos61oc06j; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukg0guo4k8krgpwuagos61oc06j UNIQUE (token);


--
-- Name: user_account user_account_pkey; Type: CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.user_account
    ADD CONSTRAINT user_account_pkey PRIMARY KEY (id);


--
-- Name: idx_inspeccion_created_at; Type: INDEX; Schema: public; Owner: estanteria_user
--

CREATE INDEX idx_inspeccion_created_at ON public.inspeccion USING btree (created_at);


--
-- Name: idx_inspeccion_estanteria_codigo; Type: INDEX; Schema: public; Owner: estanteria_user
--

CREATE INDEX idx_inspeccion_estanteria_codigo ON public.inspeccion USING btree (estanteria_codigo);


--
-- Name: ix_user_account_company_id; Type: INDEX; Schema: public; Owner: estanteria_user
--

CREATE INDEX ix_user_account_company_id ON public.user_account USING btree (company_id);


--
-- Name: ix_user_account_role; Type: INDEX; Schema: public; Owner: estanteria_user
--

CREATE INDEX ix_user_account_role ON public.user_account USING btree (role);


--
-- Name: password_reset_token fk8cg8xntjydw3wfm4k2v5ea1; Type: FK CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fk8cg8xntjydw3wfm4k2v5ea1 FOREIGN KEY (user_account_id) REFERENCES public.user_account(id);


--
-- Name: inspeccion_slot_resultado fkbjjqh4amlq5oycbwekuh89a4n; Type: FK CONSTRAINT; Schema: public; Owner: estanteria_user
--

ALTER TABLE ONLY public.inspeccion_slot_resultado
    ADD CONSTRAINT fkbjjqh4amlq5oycbwekuh89a4n FOREIGN KEY (inspeccion_id) REFERENCES public.inspeccion(inspeccion_id);


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO estanteria_user;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO estanteria_user;


--
-- PostgreSQL database dump complete
--

\unrestrict mh93ESUc69252F9VOVHfR7XglONoPxg3TdLv0sFdgYiugOgSia5CCczkHj0Cria

